# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_MACH_DREAM2LTE_EUR_OPEN) :=  \
    exynos8895-dream2lte_eur_open_07.dtb \
    exynos8895-dream2lte_eur_open_08.dtb \
    exynos8895-dream2lte_eur_open_09.dtb \
    exynos8895-dream2lte_eur_open_10.dtb

dtb-$(CONFIG_MACH_DREAM2LTE_KOR_SINGLE) :=  \
    exynos8895-dream2lte_kor_06.dtb \
    exynos8895-dream2lte_kor_07.dtb \
    exynos8895-dream2lte_kor_09.dtb \
    exynos8895-dream2lte_kor_10.dtb

dtb-$(CONFIG_MACH_DREAMLTE_EUR_OPEN) :=  \
    exynos8895-dreamlte_eur_open_05.dtb \
    exynos8895-dreamlte_eur_open_07.dtb \
    exynos8895-dreamlte_eur_open_08.dtb \
    exynos8895-dreamlte_eur_open_09.dtb \
    exynos8895-dreamlte_eur_open_10.dtb

dtb-$(CONFIG_MACH_DREAMLTE_KOR_SINGLE) :=  \
    exynos8895-dreamlte_kor_05.dtb \
    exynos8895-dreamlte_kor_07.dtb \
    exynos8895-dreamlte_kor_09.dtb \
    exynos8895-dreamlte_kor_10.dtb \
    exynos8895-dreamlte_kor_11.dtb

dtb-$(CONFIG_MACH_GREATLTE_EUR_OPEN) :=  \
    exynos8895-greatlte_eur_open_02.dtb \
    exynos8895-greatlte_eur_open_06.dtb

dtb-$(CONFIG_MACH_GREATLTE_KOR_SINGLE) :=  \
    exynos8895-greatlte_kor_02.dtb \
    exynos8895-greatlte_kor_06.dtb

always            := $(dtb-y) $(dtbo-y)
clean-files       := *.dtb*
